on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        run: action/checkout@v3
       
      - name: make script executable
        run: chmod +x ./add.sh

      - name: run deploy script
        run: ./add.sh  
